### ISSUE TITLE
Randomize color opition

### ISSUE THREAD

**Issue by Crazylegs916** [minishmaker/randomizer#16]
I play the randomizer a lot and I wish there was a randomized color opition where it randomizes the heart, tunic, and split bar color with one click

**Comment by Myth197** [comment]
Issue can be closed.
Randomize colour options introduced in 0.7, can choose to preview the random colour before generation or allow it to be hidden.
https://github.com/minishmaker/randomizer/releases/tag/v0.7.0-rc1
