### ISSUE TITLE
Figurine-sanity doesn't do anything

### ISSUE THREAD

**Issue by DragonflyShadows** [minishmaker/randomizer#18]
I spent ages trying to find a combination that would result in a seed that the randomiser considers beatable and it was only when I added open DHC + Ped Items at the end that it successfully generated, but after playing for a while and double-checking with the spoiler log, I can confirm that figurines were not shuffled.
Relevant things worth noting:
-Keysanity and shuffle traps were on
-Disable glitches was on
-The Figurine count and Extra figurines boxes react to mouse clicks as text boxes with the text disappearing on click

**Comment by wjg999** [comment]
Open DHC (and ped items by extension) disable the figurine setting as pulling the pedestal is either never done (open) or set specifically to 2-3-4 elements for the 3 items (ped items), with high figurine counts seeds have a good chance to not generate as they take major item spots meaning they go before other possibly needed items, to remedy this a bit you can use less figurines during generation or add more spots for them to be placed in by say adding the rupees to the item pool or turning on open fusions.
