### ISSUE TITLE
!replaceamount / !replaceincremental fail silently if there are not enough things to replace

### ISSUE THREAD

**Issue by Ibot02** [minishmaker/randomizer#27]
To reproduce:
Generate a spoiler log for a seed with figurine hunt (1+135), other settings as default. Check the spoiler log for how many figurines (KinstoneBags) are shuffled into the pool.

Expected behavior: The seed should fail to generate as there is not enough junk in the pool to put that many figurines into it.
Actual behavior: The seed generates, placing some number of figurines (but less than 136) into the pool.

Proposed low-effort change to work around this issue:
Make the pedestal *logically* require the total amount of figurines to be placed, instead of the actually required amount. This also prevents figurines from being placed behind the pedestal (when playing Ped Open seeds).
(This would, of course, not actually fix this issue)

**Comment by Myth197** [comment]
Resolved in #56 (Likely earlier, but definitely in this)
