### ISSUE TITLE
Logic: Weighted counting is broken

### ISSUE THREAD

**Issue by Ibot02** [minishmaker/randomizer#29]
This is most noticeable through the shop items never being considered accessible.

To reproduce:
Edit the default logic, plandoing a required item to the shop 600 spot (by making that spot it's own dungeon and having an item be shuffled to said dungeon).
Editing the requirements for rupees from the spot from `(+980, Items.Rupee1, Items.Rupee5::5, Items.Rupee20::20, Items.Rupee50::50, Items.Rupee100::100, Items.Rupee200::200)` to `(+980, Items.Rupee200::200)` will *not* cause randomization to succeed, but changing it to `(+5, Items.Rupee200)` will.

Expected behavior:
The second case should be indistinguishable from the third, while the first might lead to different randomization but no noticeable difference in generated seeds.

**Comment by wjg999** [comment]
Should have been fixed in v0.6.2a
