### ISSUE TITLE
softlock glitch (sort of)

### ISSUE THREAD

**Issue by cabij420** [minishmaker/randomizer#35]
I was playing the randomizer with all kinstone fusions complete. I entered veil falls from north hyrule field and I had the roc's cape. since all fusions were done, there was a patch of land by the diggable wall near the entrance. I used the roc's cape to jump over there (just possible), dug out the cave and tried to jump back but couldn't make it. I did not have the flippers or ocarina. The only way back that I can think of it resetting the game. Do you look for solutions to things like this or do you leave it to the player to reset the game?

Edit: lol 4 minutes later and I just find out you can quick reset. my bad!

![softlock](https://user-images.githubusercontent.com/84211072/118342660-1e7aad00-b51c-11eb-880d-5a0eb364b82b.png)

**Comment by Ibot02** [comment]
The jump backwards is possible.
You can also just quickwarp or savewarp.
