### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Bcool14** [minishmaker/randomizer#42]
Good Morning. I'm not really sure is this a problem. Sorry if I wrote in the wrong place but i have a question. I am a linux user and i would love to play this randomizer I tried using wine (a linux .exe executer) but it couldn't execute the .exe file. I was wondering is there a linux version of the Minish Cap Randommizer?

**Comment by Myth197** [comment]
As of #56, There is a Linux build that allows use of the randomizer through the CLI:
[https://github.com/minishmaker/randomizer/releases/download/v0.7.0-rc3/MinishRandomizer-v0.7.0-alpha-rev3-cli-linux-x64-hotfix.zip](https://github.com/minishmaker/randomizer/releases/download/v0.7.0-rc3/MinishRandomizer-v0.7.0-alpha-rev3-cli-linux-x64-hotfix.zip)
