### ISSUE TITLE
Randomizer assumes getting to temple of droplets with roc's cape is possible when it is not

### ISSUE THREAD

**Issue by WasabiRaptor** [minishmaker/randomizer#44]
I have exhausted every possible item I can *actually* get without having flippers, and I would assume the tracker and the generator follow the same logic, it lists two green items on the south side of Lake Hylia in addition to the first part of the temple of droplets

however, without flippers I cannot swim over to said locations, nor can I get to the south side of lake Hylia as mole mitts haven't been found yet either, leading to the situation I would assume would be an incredibly long roc's cape jump from one of the shallow water platforms on the east side down to the south, which is impossible, it comes up one tile short every time, no matter how close to the edge I start the jump, it might be possible with a frame perfect thing maybe? but that should not be within normal logic 

it might also be possible should there be a platform from kinstone fusions in the lake center but I haven't been able to fuse any kinstones either

**Comment by 21aslade** [comment]
To get that roc's cape jump, you need to extend it by tapping the button, _then_ holding it at the peak of your jump.
