### ISSUE TITLE
Option to force mini games to contain junk items

### ISSUE THREAD

**Issue by Blazingflare** [minishmaker/randomizer#45]
Self explanatory. Just a toggle so that athe various mini games, or at least the cuckoo mini game, always contain junk items.

The cuckoo mini game is hell, and I recently got a seed that locked the Pegasus boots behind the ocarina, and the ocarina behind the cuckoo catching mini game.

**Comment by Myth197** [comment]
Minigame options coming in next release
Catobat@210b197

**Comment by Myth197** [comment]
Resolved by #56
