### ISSUE TITLE
Allow Saving of Custom Colors 

### ISSUE THREAD

**Issue by jaguarnick** [minishmaker/randomizer#46]
The color picker window for tunic, heart, and split bar color has a built in save custom color section, but that window doesn't save that data if you add a custom color. Would make it much easier to reuse colors without jotting rgb values down externally. Also could save the last color used so that people who liked the colors of their last run don't need to remember to add to custom colors until changing off of a color.

**Comment by Myth197** [comment]
Issue can be closed.
Resolved in 0.7, can save Cosmetic section as either a setting string for sharing with others, or as a selectable preset for repeated use.
https://github.com/minishmaker/randomizer/releases/tag/v0.7.0-rc1
