### ISSUE TITLE
Please let players actually read the dialogue if they want

### ISSUE THREAD

**Issue by geekley** [minishmaker/randomizer#47]
Not everyone who wants to play this is a speed-runner, some just want a different way to replay the game!

Please let us read the dialogue without having to use "half-presses" or whatever.
Even with SLOW message setting in-game it's still hard to read. Some alternatives to implement this:
- Best implementation: Make it depend on button (e.g. A/R skips like in vanilla, where it's not a problem to hold the button; holding B fast-skips like now)
- Or lesser implementation: Make it fast skip only on FAST message setting in-game

Also please make the timer pause during dialogues! That's not fair! Why would a player be punished for enjoying the story?

Unrelated: Are those numbers above the timer the amount of figurines? A bit unclear in docs.

**Comment by Myth197** [comment]
Text speed option coming in next release
Catobat@2106417

**Comment by Myth197** [comment]
Resolved by #56
