### ISSUE TITLE
Can't randimize!

### ISSUE THREAD

**Issue by Linkdash2019** [minishmaker/randomizer#48]
randomization succeeded, but could not be Vatti

**Comment by Rylux** [comment]
Can you share the settings you're using ? Invalid settings combinations can cause this error to happen.

You should also try changing the seed number, as this can happen with some seeds bc of key placement.

**Comment by Linkdash2019** [comment]
![Minish Randomizer v0 6 2a 11_18_2022 1_11_41 PM](https://user-images.githubusercontent.com/110307943/202793962-d7140f5e-90a3-4915-bce4-7895494f18c1.png)

**Comment by Linkdash2019** [comment]
also rainbow hearts

**Comment by Rylux** [comment]
In your case, you're having the error bc you selected "Shuffle figurines into item pool" but didn't provide a number for firgurine count and extra figures.

- Figurine count is the number of figurines that will be required to activate the pedestal, to open DHC.
- Extra figs are additionals figurines that are going to be added to the item pool, but won't increase the number of required figurines to activate the pedestal.

The sum of those shoudn't be over 136(the original amount of figurines in the vanilla game)
