### ISSUE TITLE
Randomizer doesn't work on real GBA

### ISSUE THREAD

**Issue by MediaGemini** [minishmaker/randomizer#69]
Randomizer gives the blue screen warning when loaded onto an EZ Flash 4 Definitive Edition as well as when flashed to several repro carts I've tested. I propose an experimental toggle to disable the emulator check at users own risk when intending to use physical hardware. It is quite funny that it's flagging stock Nintendo hardware as insufficient though, got a good laugh out of it.

**Comment by mikeskydev** [comment]
The randomizer performs certain tests on the setup which are required to complete the randomizer, as those techniques are used at required points in the game progression. In this case, it's the EZ Flash 4 that will be failing the checks, I'm afraid. I believe the everdrive is compliant and will not present this message. However, you may also want to check the settings available on the EZ Flash (things like save types come to mind) to see if one of them will solve the issue.

**Comment by MediaGemini** [comment]
Changing the save type from auto to SRAM worked for the EZ Flash 4. That doesn't explain why my other repro carts won't work. I'm almost positive applying a save type patch over the randomizer will break it. And I encountered a weird error on the Ez Flash where it refuses to write the file to NOR for autobooting, a feature of the Definitive Edition that allows skipping the menu for use as Slot-2 of a DS. At least I'm able to play on my GBA SP now.
